version: '3'

services:
  ssh-proxy:
    build:
      context: ./
      dockerfile: ./docker/ssh-proxy/Dockerfile
    hostname: 'ssh-proxy'
    ports:
      - 2222:2222
    volumes:
      - ../sshr:/go/src/github.com/heat1024/sshr
    working_dir: /go/src/github.com/heat1024/sshr
    command: make server
    links:
      - host-tsurubee:host-tsurubee
      - host-hoge:host-hoge

  host-tsurubee:
    build:
      context: ./
      dockerfile: ./docker/host-tsurubee/Dockerfile
    hostname: 'host-tsurubee'

  host-hoge:
    build:
      context: ./
      dockerfile: ./docker/host-hoge/Dockerfile
    hostname: 'host-hoge'
